### ISSUE TITLE
ActivityMainBinding issue.

### ISSUE THREAD

**Issue by anukools** [danielw93/spannable-badge-example#1]
Hi daniel,
I could not find definition of ActivityMainBinding.  it has comment auto-generated but dont know how..?

**Comment by d4l-w4r** [comment]
Hey! Have you solved your Problem? The solution is that I use androids data binding feature in this example. To activate it you have to include 

dataBinding {
        enabled = true
    } 
in your build.gradle.

(See app/build.gradle)

**Comment by anukools** [comment]
yeah @danielw93  I had got the solution, so I had closed the issue.

**Comment by anukools** [comment]
hey @danielw93  one more thing I haven't used databinding yet in my project so Is there any way to assign the viewmodel without databinding to my textview.

Thanks

**Comment by anukools** [comment]
Hi @danielw93 can you please let me know how can I add click listeners on each badges..?

**Comment by d4l-w4r** [comment]
Hey sorry that I never responded...totally flew under my radar.
I have now updated the repo with the possibility of adding click listeners.

It works by simply overlaying the ReplacementSpan with a ClickableSpan (ie. render them over the same range of text). The only other modification you have to make is to set the `MovementMethod` of the TextView containing the badges to `LinkMovementMethod` in order for clicks to be registered by the TextView
